/*
 * File: app/view/CensusDetailPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RTSBapp.view.CensusDetailPanel', {
    extend: 'Ext.Container',
    alias: 'widget.censusdetailpanel',

    config: {
        cls: 'censusdetailpanel',
        height: 795,
        layout: {
            type: 'vbox'
        },
        scrollable: false,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                itemId: 'listToolbar',
                padding: '.4em 0 0 0',
                layout: {
                    align: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'censusdetailbackbtn',
                        maxWidth: 80,
                        minWidth: 80,
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'spacer',
                        width: 10
                    },
                    {
                        xtype: 'label',
                        itemId: 'censusdetaillabel',
                        maxWidth: '10em',
                        style: 'color : white'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                height: 741,
                padding: '',
                layout: {
                    animation: false,
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'container',
                        title: 'Store',
                        scrollable: false,
                        items: [
                            {
                                xtype: 'toolbar',
                                docked: 'top',
                                minHeight: '1.5em',
                                style: 'background: #5e6266; font-size: .8em;',
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'Number',
                                        style: 'text-align: right; padding-right: 1em; padding-top: .1em;',
                                        width: '66.666%'
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'right',
                                        hidden: true,
                                        html: 'Percent',
                                        style: 'padding-right: 1em; padding-top: .1em;'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                cls: 'censusfieldset1',
                                height: '70em',
                                itemId: 'censusscrollcont',
                                maxHeight: '70em',
                                minHeight: '70em',
                                layout: {
                                    type: 'hbox'
                                },
                                scrollable: 'vertical',
                                items: [
                                    {
                                        xtype: 'container',
                                        flex: 2,
                                        cls: 'censusfieldset1',
                                        height: '70em',
                                        maxHeight: '70em',
                                        minHeight: '70em',
                                        layout: {
                                            type: 'vbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'fieldset',
                                                flex: 1,
                                                height: '70em',
                                                itemId: 'censusfieldset1',
                                                maxHeight: '70em',
                                                minHeight: '70em',
                                                scrollable: false,
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        inputCls: 'detailtextfields',
                                                        label: 'Field',
                                                        labelWidth: '60%',
                                                        readOnly: true
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        cls: 'censusfieldset2',
                                        height: '70em',
                                        maxHeight: '70em',
                                        minHeight: '70em',
                                        layout: {
                                            type: 'vbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'fieldset',
                                                flex: 1,
                                                height: '70em',
                                                hidden: true,
                                                itemId: 'censusfieldset2',
                                                maxHeight: '70em',
                                                minHeight: '70em',
                                                scrollable: false,
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        hidden: true,
                                                        readOnly: true
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Map',
                        style: 'background-color:#000;overflow: hidden;',
                        layout: {
                            type: 'vbox'
                        },
                        scrollable: false,
                        items: [
                            {
                                xtype: 'image',
                                height: 1253,
                                html: '<div style="background-image:url(./resources/images/RTSB_Eastbound_EU-BALTIKUM-GUS.png);height:1024px;width:100%;background-repeat:repeat;background-size: cover;">',
                                src: './resources/images/RTSB_Eastbound_EU-BALTIKUM-GUS.png'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Details',
                        style: 'background-color:#000;overflow: hidden;',
                        layout: {
                            type: 'vbox'
                        },
                        scrollable: false,
                        items: [
                            {
                                xtype: 'image',
                                height: 1253,
                                html: '<div style="background-image:url(./resources/images/Details_bg.png);height:1024px;width:100%;background-repeat:repeat;background-size: cover;">  <p><strong><font size="4">Baltikum / Tallinn / Riga / Vilnius:</font></strong><br><br> <font size="3">- Ueberseetransporte in die baltischen Haefen und Umladung <br> - Kommissionierung<br> - Lagerung<br> - Verzollung<br> - Deklarations<br> - Zollangelegenheiten<br><br> - Blockzuege fuer Projektlogistik<br> - Bereitstellung von EVRU, LVRU Container</font><br> </p> ',
                                src: ''
                            }
                        ]
                    }
                ],
                tabBar: {
                    docked: 'top',
                    hidden: false,
                    margin: '',
                    scrollable: false,
                    layout: {
                        pack: 'center',
                        type: 'hbox'
                    }
                }
            }
        ]
    }

});