/*
 * File: app/view/EWG.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RTSB.view.CNEU', {
    extend: 'Ext.navigation.View',
    config: {
        navigationBar: {
            hidden: true
        },
        items: [
            {
                xtype: 'tabpanel',
                items: [
                    {
                        xtype: 'container',
                        title: 'Map',
                        html: [
                                                       '<div style="background-image:url(resources/loading/RTSB_Westbound_CHINA-EU.png);height:1024px;width:100%;background-repeat:no-repeat;background-size: 100%;">'

                        ].join("")
                    },
                    {
                        xtype: 'container',
                        title: 'Details',

                        /*html: [
                                 '<div style="background-image:url(resources/loading/DBGDetails.jpg);height:1024px;width:100%;background-repeat:no-repeat;background-size: 100%;">'

                        ].join("")*/
                        items: [
                                {
                                    xtype: 'button',
                                    itemId: 'myImage',
                                    text: 'Image',
                                    ui: 'action',

                                }
                        ]
                    }
                ]
            }
        ],
        listeners: [
                    {
                        fn: 'onImageClick',
                        event: 'tap',
                        delegate: '#myImage'
                    }
                    ]
    },
    onImageClick: function (button, e, eOpts)
    {
       // this.hide();
        this.push(Ext.create("RTSB.view.MyImg"), {
            title: "NestedList"
        });
    },
});