/*
 * File: app/view/EWG.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RTSBapp.view.CNEUEN', {
    extend: 'Ext.navigation.View',
    requires: [
        'Ext.TitleBar',
        'Ext.ux.PinchZoomImage',
        'Ext.Video'
    ],
    config: {
        navigationBar: {
            hidden: true
        },
        items: [
            {
                xtype: 'tabpanel',
                items: [
                    {
                        xtype: 'container',
                        title: 'Map',
                        style: 'background-color:#000',
                        items: [
                            {
                                // id: 'landscapeFormFields',
                                id: 'portraitFormFields',
                                xtype: 'pinchzoomimage',
                                layout: 'card',
                                centered: true,
                                style: 'background-color:#000;overflow: hidden;',
                                height: '100%',
                                width: '100%',
                                //maxHeight: '100%',
                                //maxWidth: '100%',
                                //minHeight: '100%',
                                //minWidth: '100%',
                                src: 'resources/loading/RTSB_Westbound_CHINA-EU.png',

                                //src: 'http://127.0.0.1/touch/apps/RTSB/resources/loading/RTSBapp_loading_bg.png'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Details',
                        scrollable: 'vertical',
                        style: 'background-color:#000;overflow: hidden;',
                        html: [
                                '<div style="background-image:url(resources/loading/Details_bg.png);height:1024px;width:100%;background-repeat:no-repeat;background-size: 100%;">'

                        ].join(""),
                        items: [
                                {
                                    xtype: 'image',
                                    layout: 'card',
                                    centered: true,
                                    //style: 'background-color:#000;overflow: hidden;',
                                    maxHeight: '100%',
                                    maxWidth: '100%',
                                    minHeight: '100%',
                                    minWidth: '100%',
                                    // src: 'resources/loading/Details_bg.png',
                                    centered: true,
                                    html: '<p>RTSB GmbH - Rail Transportation Service Broker<br>' +
                                            'Industriestrasse 27<br>' +
                                            'D-61381 Friedrichsdorf<br><br>' +

                                            'Tel.: +49 (0) 6172-5908-0<br>' +
                                            'Fax: +49 (0) 6172-7776-73<br><br>' +

                                            'Email: info@rtsb.de<br>' +
                                            'Web: www.rtsb.de <br><br>' +

                                            'HRB 6070 Bad Homburg vor der Hoehe<br>' +
                                            'Steuernummer: 003 242 88102 <br>' +
                                            'Umsatzsteuer ID: DE 191151613<br>' +
                                            'Geschaeftsfuehrer: Artur Ballardt</p>',
                                    styleHtmlContent: true,
                                    //src: 'http://127.0.0.1/touch/apps/RTSB/resources/loading/Details_bg.png'
                                }
                        ]
                    }
                ]
            }
        ]
    }

});