/*
 * File: app/view/EastBound.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RTSB.view.EastBound', {
    extend: 'Ext.navigation.View',

    config: {
        items: [
            {
                xtype: 'formpanel',
                title: 'EastBound',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'mybutton11',
                        text: 'Europa –> Weißrussland  –> GUS'
                    },
                    {
                        xtype: 'button',
                        itemId: 'mybutton12',
                        text: 'Europa –> Baltikum –> GUS'
                    },
                    {
                        xtype: 'button',
                        itemId: 'mybutton13',
                        text: 'Europa –> Ukraine –> GUS'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'container',
                        title: 'About',
                        iconCls: 'home',
                        itemId: 'mycontainer36'
                    },
                    {
                        xtype: 'container',
                        title: 'Settings',
                        iconCls: 'settings'
                    },
                    {
                        xtype: 'titlebar',
                        iconCls: 'user',
                        itemId: 'mycontainer38',
                        title: 'User'
                    }
                ],
                tabBar: {
                    docked: 'bottom'
                }
            }
        ],
        listeners: [
            {
                fn: 'onMybutton11Tap',
                event: 'tap',
                delegate: '#mybutton11'
            },
            {
                fn: 'onMybutton12Tap',
                event: 'tap',
                delegate: '#mybutton12'
            },
            {
                fn: 'onMybutton13Tap',
                event: 'tap',
                delegate: '#mybutton13'
            }
        ]
    },

    onMybutton11Tap: function(button, e, eOpts) {
        this.push(Ext.create("RTSB.view.EWG"), {
            title: "NestedList"
        });
    },

    onMybutton12Tap: function(button, e, eOpts) {
        this.push(Ext.create("RTSB.view.EBG"), {
            title: "NestedList"
        });
    },

    onMybutton13Tap: function(button, e, eOpts) {
        this.push(Ext.create("RTSB.view.EUG"), {
            title: "NestedList"
        });
    }

});