/*
 * File: app/view/EWG.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RTSB.view.EWG', {
    extend: 'Ext.navigation.View',

    config: {
        items: [
            {
                xtype: 'formpanel',
                title: 'EWG',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'tabpanel',
                                items: [
                                    {
                                        xtype: 'container',
                                        title: 'Option 1'
                                    },
                                    {
                                        xtype: 'container',
                                        title: 'Option 2'
                                    },
                                    {
                                        xtype: 'container',
                                        title: 'Option 3'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'map',
                        height: 385
                    }
                ]
            }
        ]
    }

});