/*
 * File: app/view/Impressum.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RTSB.view.Impressum', {
    extend: 'Ext.navigation.View',

    config: {
        height: 478,
        items: [
            {
                xtype: 'formpanel',
                title: 'Impressum',
                ui: 'dark',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'tabpanel',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'container',
                                title: 'Tab 1',
                                iconCls: 'info'
                            },
                            {
                                xtype: 'container',
                                title: 'Tab 2',
                                iconCls: 'info'
                            },
                            {
                                xtype: 'container',
                                title: 'Tab 3',
                                iconCls: 'info'
                            }
                        ],
                        tabBar: {
                            docked: 'bottom'
                        }
                    },
                    {
                        xtype: 'textfield',
                        centered: false,
                        height: 56,
                        hidden: false,
                        label: 'RTSB GmbH - Rail Transportation Service Broker',
                        labelAlign: 'top',
                        labelWidth: '100%',
                        labelWrap: true
                    },
                    {
                        xtype: 'textfield',
                        height: 28,
                        label: 'Industriestrasse 27',
                        labelWidth: '100%',
                        labelWrap: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'D-61381 Friedrichsdorf',
                        labelWidth: '100%',
                        labelWrap: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Tel.: +49 (0) 6172-5908-0',
                        labelWidth: '100%',
                        labelWrap: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Fax: +49 (0) 6172-7776-73',
                        labelWidth: '100%',
                        labelWrap: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Email: info@rtsb.de',
                        labelWidth: '100%',
                        labelWrap: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Web: www.rtsb.de',
                        labelWidth: '100%'
                    },
                    {
                        xtype: 'textfield',
                        label: 'HRB 6070 Bad Homburg vor der Höhe',
                        labelWidth: '100%',
                        labelWrap: true
                    }
                ]
            }
        ]
    }

});