/*
 * File: app/view/MyPanel1.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('RTSBapp.view.MyPanel1', {
    extend: 'RTSBapp.view.ui.MyPanel1',

    initialize: function() {
        var me = this;
        me.callParent(arguments);
    },

    onMybuttonTap: function(button, e, options) {
        if (!this.popup) {
            this.popup = Ext.Viewport.add({
                xtype: 'myoverlay'
            });
        }
        this.popup.show();
    }

});