/*
 * File: app/view/NestedList.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RTSB.view.NestedList', {
    extend: 'Ext.navigation.View',

    config: {
        title: 'Nested List',
        items: [
            {
                items: [
                    {
                        xtype: 'tabpanel',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'container',
                                title: 'About',
                                iconCls: 'home',
                                itemId: 'mycontainer36'
                            },
                            {
                                xtype: 'container',
                                title: 'Settings',
                                iconCls: 'settings'
                            },
                            {
                                xtype: 'titlebar',
                                iconCls: 'user',
                                itemId: 'mycontainer38',
                                title: 'User'
                            }
                        ],
                        tabBar: {
                            docked: 'bottom'
                        }
                    },
                    {
                        xtype: 'button',
                        itemId: 'mybutton19',
                        text: 'Eastbound Routes & Services Europe – Russland – Zentralasien'
                    },
                    {
                        xtype: 'button',
                        text: 'China Routes & Services'
                    },
                    {
                        xtype: 'button',
                        text: 'RZD Frachtzahlercode'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybutton19Tap',
                event: 'tap',
                delegate: '#mybutton19'
            }
        ]
    },

    onMybutton19Tap: function(button, e, eOpts) {
        this.push(Ext.create("RTSB.view.EastBound"), {
            title: "NestedList"
        });
    }

});