/*
 * File: app/view/NestedList.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RTSBapp.view.RussianPanel', {
    extend: 'Ext.navigation.View',
    config: {
        navigationBar: {
            hidden: true
        },
        title: 'Russian Panel',
        items: [
            {
                xtype: 'panel',
                minHeight: '100%',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'EastBoundButton',
                        minHeight: '50%',
                        text: 'EastBound'
                    },
                    {
                        xtype: 'button',
                        itemId: 'ChinaButton',
                        minHeight: '50%',
                        text: 'China'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onEastBoundTap',
                event: 'tap',
                delegate: '#EastBoundButton'
            },
            {
                fn: 'OnChinaTap',
                event: 'tap',
                delegate: '#ChinaButton'
            }
        ]
    },

    onEastBoundTap: function (button, e, eOpts) {
        this.push(Ext.create("RTSBapp.view.EastBoundRu"), {
            title: "EastBound Panel"
        });
    },

    OnChinaTap: function (button, e, eOpts) {
        this.push(Ext.create("RTSBapp.view.CNEURU"), {
            title: "EastBound Panel"
        });
    }

});