/*
 * File: app/view/ui/MyOverlay.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RTSBapp.view.ui.MyOverlay', {
    extend: 'Ext.Panel',

    config: {
        centered: true,
        html: '<p>RTSB GmbH - Rail Transportation Service Broker<br>'+
                'Industriestrasse 27<br>' +
                'D-61381 Friedrichsdorf<br>' +

                'Tel.: +49 (0) 6172-5908-0<br>' +
                'Fax: +49 (0) 6172-7776-73<br>' +

                'Email: info@rtsb.de<br>' +
                'Web: www.rtsb.de <br>' +

                'HRB 6070 Bad Homburg vor der Höhe<br>' +
                'Steuernummer: 003 242 88102 <br>' +
                'Umsatzsteuer ID: DE 191151613<br>' +
                'Geschäftsführer: Artur Ballardt</p>',
        styleHtmlContent: true,
        modal: true,
        scrollable: 'vertical',
        height: '80%',
        width: '80%',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Impressum',
                layout: {
                    pack: 'end',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        ui: 'decline',
                        text: 'x',
                        itemId: 'mybutton',
                    }
                ]
            }
        ],
        listeners: [
        {
            fn: 'onMybuttonTap',
            event: 'tap',
            delegate: '#mybutton'
        }
        ]
    },
    onMybuttonTap: function (button, e, options) {
        this.hide();
    }

});