/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    paths: {
        'Ext.ux': 'libs/ux'
    }
});

Ext.application({

    requires: [
        'Ext.MessageBox',
        'Ext.ux.PinchZoomImage'
    ],
    stores: [
        'OverrideStore',
        'CensusFilterStore'
    ],
    views: [
        'Main',
        'TouchTreeGrid',
        'griddetailpanel',
        'GridHelpPanel',
        'RTSBapp',
        'HomeImage',
        'GUIMAP',
        'SettingsPanel',
        'MyContainer110'
    ],
    controllers: [
        'CommonController',
        'TasksController',
        'ListsController',
        'CensusController',
        'ProjectController'
    ],
    name: 'TouchTreeGrid',

    launch: function() {

        Ext.Viewport.add(Ext.create('TouchTreeGrid.view.RTSBapp'));

        // redraw image when orientation is changed. 
        Ext.getDom('ext-viewport').addEventListener('orientationchange', function() {

            var pinchzooms = Ext.ComponentQuery.query('pinchzoomimage');
            for (var i=0;i<pinchzooms.length;i++) {
                pinchzooms[i].redraw();
            }
        });
    }

});
